services:
  - type: web
    name: odds-tracker  # Benzersiz isim
    env: python3.9      # Kesin Python sürümü
    plan: free          # Ücretsiz plan
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: DROP_THRESHOLD
        value: "0.10"
    healthCheckPath: /  # Sağlık kontrolü
    autoDeploy: true    # Otomatik deployment
