services:
  - type: web
    name: oran-dusus-render-full
    env: python3.9  # Spesifik Python sürümü
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DROP_THRESHOLD
        value: "0.10"
