services:
  - type: web
    name: odds-tracker
    env: python3.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: DROP_THRESHOLD
        value: "0.10"
